### ISSUE TITLE
Setting up pebble error 

### ISSUE THREAD

**Issue by YonasBerhe** [pebble-dev/RebbleOS#99]
![Screenshot_20200314-031337_Pebble-Rebble](https://user-images.githubusercontent.com/8443899/76680043-9826ac00-65a2-11ea-9b35-29618d1b3b94.jpg)

**Comment by UDXS** [comment]
This is not the correct place to report this issue. Please join the [Rebble Discord server here](http://discord.gg/aRUAYFN) and ask in #rebble-help.

**Comment by Willow-Systems** [comment]
Hi @YonasBerhe. The issue you're seeing is because the app you're using is trying to load rebble over plaintext HTTP, which isn't allowed for auth. Please not that the 'rebble app' on the Google Play store is not an official rebble app, and therefore won't (and can't) be fixed by us.

For the official guide to setting up your android device, please see https://rebble.io/howto

**Comment by YonasBerhe** [comment]
Got it to work by not using the play store version of rebble for pebble and instead using the rebble docs
